name: Build rtl_433 images


on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_rtl_433:
    name: Build rtl_433 addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64, i386]

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Check to see if master has changed upstream
      run: ./check_release.sh
      shell:
        bash

    - name: Build rtl_433 image
      uses: home-assistant/builder@master
      if: github.event.pull_request.head.repo.full_name != github.repository
      with:
        args: |
          --test \
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-rtl_433-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target rtl_433

    - name: Build and push rtl_433 image
      uses: deviantintegral/builder@master
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        args: |
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-rtl_433-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target rtl_433

  build_rtl_433_mqtt_autodiscovery:
    name: Build rtl_433_mqtt_autodiscovery addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64, i386]

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Check to see if master has changed upstream
      run: ./check_release.sh
      shell:
        bash

    - name: Build rtl_433_mqtt_autodiscovery image
      uses: home-assistant/builder@master
      if: github.event.pull_request.head.repo.full_name != github.repository
      with:
        args: |
          --test \
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-rtl_433_mqtt_autodiscovery-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target rtl_433_mqtt_autodiscovery

    - name: Build and push rtl_433_mqtt_autodiscovery image
      uses: deviantintegral/builder@master
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        args: |
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-rtl_433_mqtt_autodiscovery-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target rtl_433_mqtt_autodiscovery
